### ISSUE TITLE
Problem with module

### ISSUE THREAD

**Issue by ddevlin13** [Kekilla0/whisper-dialog#13]
I installed your module and at first it worked, although the chat button wasn't created.

However, now it fails with an error in the console.  Screenshots below.

Thank you for taking the time to look at this.

![image](https://user-images.githubusercontent.com/12978102/122658791-64d8b280-d13f-11eb-88e5-44f880112463.png)

![image](https://user-images.githubusercontent.com/12978102/122658775-2b07ac00-d13f-11eb-99b8-17c094f5af1e.png)

![image](https://user-images.githubusercontent.com/12978102/122658778-31962380-d13f-11eb-9bbf-76c4e4ef4ff5.png)

![image](https://user-images.githubusercontent.com/12978102/122658780-38249b00-d13f-11eb-82f6-008456fa8067.png)

**Comment by Kekilla0** [comment]
yep, thats a problem. 
No idea why its doing this but ill fix it in the next 2 or 3 days.

**Comment by ddevlin13** [comment]
Thanks!

**Comment by Kekilla0** [comment]
Alright this problem was two fold 
1. It wasn't supposed to be looking for a setting
2. You didn't have a user connected, so it was throwing an error.
