### ISSUE TITLE
Unreliable chat button

### ISSUE THREAD

**Issue by Meckerdrache** [Kekilla0/whisper-dialog#14]
The chat button is sometimes there and sometimes it isn't. Sometimes it reappears after restarting the game and sometimes it does when I change the module settings and then change them back again. I have not yet found any connection to other modules or anything really. It seems to be random.

**Comment by Kekilla0** [comment]
Need a bit more information, version and other modules would be a start 

On both my 0.8.6 and 0.8.7 worlds I had no issue

**Comment by MJDesrochers** [comment]
I'm on version 0.8.7 and this button has never appeared.

**Comment by Kekilla0** [comment]
Think i figured it out, the chat window is reRendering after the ready hook and causing the HTML to get lost. Working on it now.

**Comment by Kekilla0** [comment]
Yeah should be fixed in like an hour. Updated and Uploaded.

**Comment by Kekilla0** [comment]
Update pushed
