### ISSUE TITLE
Better Format

### ISSUE THREAD

**Issue by brunocalado** [Kekilla0/whisper-dialog#15]
Hi.

I got 5 players and the position from the checkbox is a little confusing.

![image](https://user-images.githubusercontent.com/4999783/124942584-26b60c80-dfe2-11eb-9d3f-d07f09594f53.png)

Can you improve it a little? Just move the name to the right of the checkbox or something.

Thank you

**Comment by Kekilla0** [comment]
It shouldn't look like that at all

**Comment by Kekilla0** [comment]
Can you give me a list of modules you have installed, This should look completely different. 
![Test](https://i.gyazo.com/473762caa7cf4324936f4d3edeeb365e.png)
This is a image of the test i just ran

**Comment by brunocalado** [comment]
I turn off:
- minimal
- chat enhacements



autoanimations--v.4.08;
autorotate--v1.2.1;
betterrolls-swade2--v.36;
cardsupport--v.6.1;
chatgifs--v.0.2;
chat-images--v.5.3;
chatreactions--v.4.0;
_CodeMirror--v.58.3-fvtt3;
combat-utility-belt--v.6.0;
CommunityLighting--v.4.7;
compendium-folders--v.3.2;
deadlands-core-rules--v.0.1;
df-chat-cards--v.2.2;
df-chat-enhance--v.2.0;
dfreds-droppables--v.2.7;
dice-so-nice--v.0.1;
dice-calculator--v.6.9;
DragTransfer--v.2.1;
drag-ruler--v.7.7;
forien-copy-environment--v.0.5;
foundryvtt-arms-reach--v.2.2;
fxmaster--v.2.1;
gm-notes--v.4.1;
illandril-token-hud-scale--v.4.1;
keybind-lib--v.3.2;
colorsettings--v.5.9;
_chatcommands--v.3.3;
lib-find-the-path--v.4.0;
lib-wrapper--v.7.5.0;
macro-folders--v.2.22;
swademacros--v.2.6;
_mathjs--v.5.1-fvtt2;
merchantsheetnpc--v.1.5;
minimal-ui--v.0.4;
moulinette-core--v.1.8;
moulinette-gameicons--v.1.0;
moulinette-scenes--v.7.0;
moulinette-sounds--v.6.0;
moulinette-tiles--v.1.1;
mymaps--v.0.0;
narrator-tools--v.59;
Next-Up--v.1.05;
patrol--v.6.6;
pdfoundry--v.8.10;
permission_viewer--v.8.7;
playlist-enhancer--v.1.2;
pointer--v.3.3;
pt-BR--v.8.0;
quick-insert--v.4.7;
fateroll--v.4.5;
swade-core-rules--v.0.4;
settings-extender--v.1.6+0.8.6;
foundryvtt-simple-calendar--v1.2.113;
smalltime--v.9.9;
smarttarget--v.5.2;
socketlib--v.0.8;
SocketSettings--v.0.5;
_sortablejs--v.10.2-fvtt1;
swadecore--v.0.0;
swim--v.9.0;
swade-sfx-and-vfx-enchantments--v.0.0;
theatre--v.17.0;
tidy-ui_game-settings--v.1.23;
token-attacher--v.1.2;
token-hud-wildcard--v.3.1;
vtta-tokenizer--v.2.5;
tokenmagic--v.5.2.1;
token-tooltip-alt--v3.0.0;
turnAlert--v.0.0;
whisper-dialog--v.2.1;

**Comment by Kekilla0** [comment]
were you able to get any resolution on your issue?

**Comment by brunocalado** [comment]
No.

This is in my game:
![image](https://user-images.githubusercontent.com/4999783/125365825-58fd9c00-e34b-11eb-810e-dd1c648c47e4.png)


Empty world
![image](https://user-images.githubusercontent.com/4999783/125365936-86e2e080-e34b-11eb-875b-76e6da58f391.png)

**Comment by Kekilla0** [comment]
Yeah, I am unable to reproduce this. 
Have you attempted to uninstall and reinstall?

**Comment by brunocalado** [comment]
I tried now. Same thing.

I deleted the folder and installed again

**Comment by Kekilla0** [comment]
without having access to your world, i really have no clue as to what could be happening.
that appears to be specifically a css problem, also from my testing with the same modules i am not having this issue.

if you find out more, i am more that happy to help out.

**Comment by brunocalado** [comment]
I can give you access

Can I call @Kekilla#7036 ?

**Comment by Kekilla0** [comment]
just send me a message, ill get back to you when i have time. might not be for a few days (going on shift work tomorrow)

**Comment by Kekilla0** [comment]
without more information i can't help with whatever issue it is you are having.
