### ISSUE TITLE
Request: Ability to whisper to multiple users

### ISSUE THREAD

**Issue by schultzcole** [Kekilla0/whisper-dialog#3]
It would be convenient to be able to send a whisper dialog to multiple users, at least programmatically. Ideally, `users` would be an array of user IDs, which, if empty, would indicate that the dialog is "public" and alerts all users, exactly how the `whisper` property of chat messages works.

**Comment by Kekilla0** [comment]
Should be implemented. Keeping this open so you can provide feedback if needed.
